### PR TITLE
fixes ENGIN-1274 add submission details page

### PR DESCRIPTION
**Pull request by jfwu90**
image

---

image

### CODE REVIEW

**Comment by garrettmaring** [comment]
@jfwu90 good to keep this open to push hook-up changes to when @tjsharp1's work on [1109](https://linear.app/engi/issue/ENGIN-1109/add-submissions-apis) is complete?

**Comment by garrettmaring** [comment]
@jfwu90 user info API PR merged, building [here](https://app.circleci.com/pipelines/github/engi-network/engi-blockchain-gql), then should be good to finalize this and merge

**Comment by garrettmaring** [comment]
include [tests](https://github.com/engi-network/engi-blockchain-gql/pull/100) and timestamp in submissions

**Comment by jfwu90** [comment]
Will update when tests PR is merged. Also need timestamp to be added.

**Comment by garrettmaring** [comment]
was merged (assuming with timestamp cc @tjsharp1)

**Review by garrettmaring — APPROVED** [review]

**Pull request merged**
